---
title: "subgroups"
author: "Dr. Suat ATAN"
date: "05 04 2021"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(igraph)
g <- graph_from_literal(A---B,B---C,A---D,A---E,B--E,E---D,D---F)
plot(g)
```

# Cliques
```{r}
cliques(g)
```

# Cliques for complex network

```{r}
df2 <- read.csv("../data/02.csv")
g2 <- graph_from_data_frame(df2)
plot(g2)

```


```{r}
cliques(g2,min=3)
```

# K-Core

```{r}
coreness(g)
```
# Colorize K-Core

```{r}
g <- set_vertex_attr(g,"core",index= V(g),coreness(g))
```


```{r}
V(g)$core
```
```{r}
V(g)$color = ifelse(V(g)$core ==1,"red","green")
```

```{r}
plot(g)
```

# K-Core For Complex Network

```{r}
df2 <- read.csv("../data/02.csv")
g2 <- graph_from_data_frame(df2)
plot(g2)
```



```{r}
g2 <- set_vertex_attr(g2,"core",index= V(g2),coreness(g2))
V(g2)$color = ifelse(V(g2)$core ==1,"red","green")
plot(g2)
```
# Modularity

```{r}
library(igraph)
g1<-graph.formula(A-B-C-A,D-E-F-D,G-H-I-G,A-D-G-A)
V(g1)$grp_good<-c(1,1,1,2,2,2,3,3,3)
V(g1)$grp_bad<-c(1,2,3,2,3,1,3,1,2)
```

# Case 1: Xenophobic

```{r}
moda <- read.csv("../data/modular-a.csv")
moda
```


```{r}
gmoda <- graph_from_data_frame(moda,directed = FALSE)
grepl("ov","raskov")
V(gmoda)$origin = ifelse(grepl("ov",V(gmoda)$name),"russian","turkish")
V(gmoda)$color = ifelse(grepl("ov",V(gmoda)$name),"blue","red")
V(gmoda)$origin_id = ifelse(grepl("ov",V(gmoda)$name),1,2)
V(gmoda)$origin
```

```{r}
plot(gmoda,
     vertex.color=V(gmoda)$color,
     vertex.size=10,
     vertex.label.color="black",
     vertex.label.cex=1.1,
     layout= layout.fruchterman.reingold(gmoda))

```

```{r}
modularity(gmoda,V(gmoda)$origin_id,)
```
# Case 2: Multicultural 

```{r}
modb <- read.csv("../data/modular-b.csv")
modb

```


```{r}
gmodb <- graph_from_data_frame(modb,directed = FALSE)
V(gmodb)$origin = ifelse(grepl("ov",V(gmodb)$name),"russian","turkish")
V(gmodb)$color = ifelse(grepl("ov",V(gmodb)$name),"blue","red")
V(gmodb)$origin_id = ifelse(grepl("ov",V(gmodb)$name),1,2)
V(gmodb)$origin

```

```{r}
plot(gmodb,
     vertex.color=V(gmodb)$color,
     vertex.size=10,
     vertex.label.color="black",
     vertex.label.cex=1.1,
     layout= layout.fruchterman.reingold(gmodb))

```

```{r}
modularity(gmodb,V(gmodb)$origin_id)
```

